services:
  - type: web
    name: caboncampus-backend
    runtime: docker
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: CabOnCampus
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_USERNAME
        value: default
      - key: REDIS_PASSWORD
        sync: false
